spring.application.name=UsFit

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/usfit?serverTimezone=Asia/Seoul}
spring.datasource.username=${DB_USER:appuser}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA setting
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# Kakao OAuth
kakao.oauth.client-id=${KAKAO_CLIENT_ID:}
kakao.oauth.client-secret=${KAKAO_CLIENT_SECRET:}
kakao.oauth.redirect-uri=${KAKAO_REDIRECT_URI:http://localhost:8080/oauth2/callback/kakao}
kakao.oauth.token-uri=${KAKAO_TOKEN_URI:https://kauth.kakao.com/oauth/token}
kakao.oauth.authorize-uri=${KAKAO_AUTHORIZE_URI:https://kauth.kakao.com/oauth/authorize}
kakao.oauth.user-info-uri=${KAKAO_USER_INFO_URI:https://kapi.kakao.com/v2/user/me}
